// Firestore data layer for the `subscribers` collection — the single
// source of truth for both print and digital subscribers across platform,
// printmanager, and (later) circulation-app. See SCHEMAS.md for the full
// schema; the short version is each doc has identity fields + an optional
// `print` block + an optional `digital` block.
//
// One person = one doc. If the same email shows up via a print signup and
// later a digital signup (or vice versa), we merge into the existing doc
// instead of creating a duplicate. `bundleType` is computed on every
// write so dashboards can filter without recomputing client-side.

import { FieldValue } from 'firebase-admin/firestore';
import { db } from './firebase-admin';

const COL = 'subscribers';

// ---- ID + slug helpers ----

// Stable doc id from email when we have one; falls back to printmanager id
// or an autogenerated id. We avoid Firestore auto-IDs for email-keyed docs
// so two paths (print signup + digital signup) converge on the same record.
function slugFromEmail(email) {
  if (!email) return null;
  return email.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 100);
}

function nowIso() {
  return new Date().toISOString();
}

// ---- bundleType resolver ----

// Reduces (print, digital) pair to one of the dashboard buckets. Order
// matters — comp wins over everything because comps need their own
// renewal logic.
export function resolveBundleType({ print, digital }) {
  if (digital?.source === 'comp' || print?.plan === 'comp') return 'comp';
  if (print?.active && !digital) return 'print-only-no-email';
  if (print?.active && digital?.hasClaimed) return 'print-bundle-active';
  if (print?.active && digital) return 'print-bundle-unclaimed';
  if (digital?.active) return 'digital-only';
  return 'print-only-no-email';
}

// ---- Serialization ----

function serialize(docSnap) {
  const data = docSnap.data();
  if (!data) return null;
  const out = { id: docSnap.id, ...data };
  for (const [k, v] of Object.entries(out)) {
    if (v && typeof v === 'object' && typeof v.toDate === 'function') {
      out[k] = v.toDate().toISOString();
    }
  }
  return out;
}

// ---- Read API ----

export async function getSubscriberById(id) {
  const snap = await db.collection(COL).doc(id).get();
  return snap.exists ? serialize(snap) : null;
}

export async function findSubscriberByEmail(email) {
  if (!email) return null;
  const emailLower = email.toLowerCase();
  // Try the deterministic id first — fast path.
  const slug = slugFromEmail(email);
  if (slug) {
    const direct = await db.collection(COL).doc(slug).get();
    if (direct.exists) return serialize(direct);
  }
  // Fall back to a query on emailLower for legacy docs created with a
  // non-email id (e.g. printmanager imports).
  const snap = await db.collection(COL).where('emailLower', '==', emailLower).limit(1).get();
  if (snap.empty) return null;
  return serialize(snap.docs[0]);
}

export async function findSubscriberByPrintManagerId(printManagerId) {
  if (printManagerId == null) return null;
  const snap = await db.collection(COL).where('print.printManagerId', '==', Number(printManagerId)).limit(1).get();
  if (snap.empty) return null;
  return serialize(snap.docs[0]);
}

export async function listSubscribers({ bundleType, limit = 100 } = {}) {
  let q = db.collection(COL).orderBy('updatedAt', 'desc').limit(limit * 2);
  const snap = await q.get();
  let rows = snap.docs.map(serialize);
  if (bundleType) rows = rows.filter(r => r.bundleType === bundleType);
  return rows.slice(0, limit);
}

// ---- Write API ----

// Upsert from the print side (printmanager Add Subscriber form, or bulk
// import). If an email is supplied AND no digital block exists yet, we
// auto-stamp `digital: { active: true, source: 'print-bundle', hasClaimed: false }`
// so the welcome-email flow knows to send a claim link.
export async function upsertPrintSubscriber({
  email,
  name,
  phone,
  address,
  print, // { plan, edition, deliveryMethod, startDate, endDate, printManagerId, carrierRoute }
  source = 'printmanager',
  tags = [],
}) {
  if (!print || !print.printManagerId) {
    throw new Error('upsertPrintSubscriber requires print.printManagerId');
  }

  const emailLower = email ? email.toLowerCase() : null;
  const existing = email
    ? await findSubscriberByEmail(email)
    : await findSubscriberByPrintManagerId(print.printManagerId);

  const docId = existing?.id || slugFromEmail(email) || `pm-${print.printManagerId}`;
  const ref = db.collection(COL).doc(docId);

  const printBlock = {
    active: true,
    plan: print.plan || 'daily-7day',
    edition: print.edition || null,
    deliveryMethod: print.deliveryMethod || 'carrier',
    startDate: print.startDate || nowIso(),
    endDate: print.endDate || null,
    printManagerId: Number(print.printManagerId),
    carrierRoute: print.carrierRoute || null,
  };

  // Auto-create digital block when an email is present and we don't
  // already have one. This is the trigger that makes the welcome-email
  // flow eligible — see /api/subscribers/[id]/send-claim.
  let digitalBlock = existing?.digital || null;
  if (email && !digitalBlock) {
    digitalBlock = {
      active: true,
      source: 'print-bundle',
      plan: null,
      startDate: nowIso(),
      hasClaimed: false,
    };
  }

  const merged = {
    email: email || existing?.email || null,
    emailLower,
    firebaseUid: existing?.firebaseUid || null,
    name: name || existing?.name || '',
    phone: phone || existing?.phone || null,
    address: address || existing?.address || null,
    print: printBlock,
    digital: digitalBlock,
    tags: Array.from(new Set([...(existing?.tags || []), ...tags])),
    source: existing?.source || source,
    createdAt: existing?.createdAt || nowIso(),
    updatedAt: nowIso(),
  };
  merged.bundleType = resolveBundleType({ print: merged.print, digital: merged.digital });

  await ref.set(merged, { merge: false });
  return { id: docId, ...merged };
}

// Upsert from the digital side (platform /subscribe, Stripe webhook, or
// admin manual add). If a print block exists for the same email we leave
// it alone — circulation owns that record.
export async function upsertDigitalSubscriber({
  email,
  name,
  phone,
  digital, // { source, plan, stripeCustomerId, stripeSubscriptionId, currentPeriodEnd }
  tags = [],
}) {
  if (!email) throw new Error('upsertDigitalSubscriber requires email');

  const existing = await findSubscriberByEmail(email);
  const docId = existing?.id || slugFromEmail(email);
  const ref = db.collection(COL).doc(docId);

  const digitalBlock = {
    active: true,
    source: digital?.source || 'paid-digital',
    plan: digital?.plan || 'all-access',
    stripeCustomerId: digital?.stripeCustomerId || existing?.digital?.stripeCustomerId || null,
    stripeSubscriptionId: digital?.stripeSubscriptionId || existing?.digital?.stripeSubscriptionId || null,
    startDate: existing?.digital?.startDate || nowIso(),
    currentPeriodEnd: digital?.currentPeriodEnd || existing?.digital?.currentPeriodEnd || null,
    hasClaimed: existing?.digital?.hasClaimed || false,
    claimEmailSentAt: existing?.digital?.claimEmailSentAt || null,
  };

  const merged = {
    email,
    emailLower: email.toLowerCase(),
    firebaseUid: existing?.firebaseUid || null,
    name: name || existing?.name || '',
    phone: phone || existing?.phone || null,
    address: existing?.address || null,
    print: existing?.print || null,
    digital: digitalBlock,
    tags: Array.from(new Set([...(existing?.tags || []), ...tags])),
    source: existing?.source || 'platform-signup',
    createdAt: existing?.createdAt || nowIso(),
    updatedAt: nowIso(),
  };
  merged.bundleType = resolveBundleType({ print: merged.print, digital: merged.digital });

  await ref.set(merged, { merge: false });
  return { id: docId, ...merged };
}

// Called from the claim-link landing page after the reader has signed in
// via Firebase Auth email-link. Stamps the firebaseUid + flips
// hasClaimed=true.
export async function markSubscriberClaimed(id, firebaseUid) {
  const ref = db.collection(COL).doc(id);
  await ref.update({
    firebaseUid,
    'digital.hasClaimed': true,
    'digital.active': true,
    updatedAt: nowIso(),
    bundleType: 'print-bundle-active',
  });
}

// Stamp that we sent a claim email so we don't keep re-sending on reload.
export async function markClaimEmailSent(id) {
  const ref = db.collection(COL).doc(id);
  await ref.update({
    'digital.claimEmailSentAt': nowIso(),
    updatedAt: nowIso(),
  });
}

// Resolve digital access for a Firebase user — used by the paywall.
// Returns null if no subscriber doc, or { active, plan, currentPeriodEnd }
// if they have a digital record.
export async function getDigitalAccessForUser(firebaseUid) {
  if (!firebaseUid) return null;
  const snap = await db.collection(COL).where('firebaseUid', '==', firebaseUid).limit(1).get();
  if (snap.empty) return null;
  const sub = serialize(snap.docs[0]);
  if (!sub.digital?.active) return null;
  return {
    active: true,
    plan: sub.digital.plan,
    source: sub.digital.source,
    currentPeriodEnd: sub.digital.currentPeriodEnd,
  };
}

// Soft-delete — flips active flags but preserves the record for audit.
export async function deactivateSubscriber(id, { reason } = {}) {
  const ref = db.collection(COL).doc(id);
  await ref.update({
    'print.active': false,
    'digital.active': false,
    deactivatedAt: nowIso(),
    deactivationReason: reason || null,
    updatedAt: nowIso(),
    bundleType: FieldValue.delete(),
  });
}
